server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:h2:mem:testdb       # in-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
      hibernate:
        ddl-auto: update            # auto-creates tables based on entities
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console